language: node_js
node_js: node
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 9cf3......9f6d
    secure: IjW3nZzoG5q6lGw/RERgH6A8xUM6UYBHr1ZznBiwErSXx3hi6DIpmhMylUS8LeLh6PPlEmFZtPm9o2kUmG1T/zKkET7AKk8adtGCRbmnjCdOejX7AbpsQERkE7eW2JN0a80Tf/ohTkE8ipFL2VtpRwsrtJBI5xTVAWHtOsnT2HJsidq+b0NPaCFIY3gRdqcqD4sISDxGLkrc+9Xc4ENbYM40w58ge6KqN4wKJu4YFHKN6VB/hKuJpq/43InT0WuzgY0HQvISoQLCREqB9TlNnU5rBHhfGQpPY99vPAgffP7Or2JJOcQHHxjSkvQunOA4t8mvU34ZEQyMJYv/ifF42JnI9eBgxylp6dMIX2e1IOZQzu4pym1uwFqQ8XUlsO5GRbwiOpfUuzOrvAXavyrvNMSyJBmkFe0GwMyZ3vzqivXHxa69MbjokVqu/x+Z4mF3Q2ufLZUOLXNaZjcs98UyoG8GHILLI3hC6VhFD4cpQaP/cT/jrsQOmFmUIQ3KIJkh2IRPkAk+DSxJxBanEtLITepJ2fJfxyiMoJamXK1wquzhxj1HaQr5+k1KSZyYa8IeEyKNV2HByL+UfR4wqiOnT6dQXIFjsipc1x28+lmf3keO5i4espi3oTXSMWPAKm6vuMt6Fz6RJJ+NbhyQ7yVs5PN2/gA8LV1Q8SI/Uc2vTCo=
  on:
    tags: true
    repo: BrightspaceUI/intl
